sensors: fix PWM available field.
YADRO-KNS/obmc-yadro-webapp pull request #17
Opened 2022-10-28 13:19 UTC by ikmsk10

The Fan PWM sensors hasn't
`xyz.openbmc_project.State.Decorator.Availability` interface, so the Available state is not determinated. It is requred to force set the Available field into true.

End-user-impact: Now Fan PWM sensors always provide `Available` field
                 that is set into `true`.

2022-10-28 17:01 UTC, nest1ing approved these changes

2022-10-28 17:01 UTC, nest1ing commented on src/sensors.hpp
> +                // Several sensors might haven't the
Some sensor doesn't implement 'sensorAvailabilityInterface' ...

2022-10-31 14:05 UTC, AlexanderAmelkin requested changes

2022-10-31 14:09 UTC, ikmsk10 commented on src/sensors.hpp
> +                // Several sensors might haven't the
fixed

2022-10-31 14:13 UTC, ikmsk10 commented on src/sensors.hpp
> +                // Force set to true for their
fixed

2022-10-31 15:33 UTC, AlexanderAmelkin approved these changes

2022-10-31 15:33 UTC, merged